widgets_search = [
    "actionReset",
    "actionLoad",
    "actionSave",
    # "menuDateityp",
    # "menuSage",
    # "menuNeu",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    # "label_update",
    "combobox_searchtype",
    "label_aufgabentyp",
    "combobox_aufgabentyp",
    "groupBox_ausgew_gk",
    "groupBox_af",
    "groupBox_gk",
    "groupBox_klassen",
    "groupBox_themen_klasse",
    "groupBox_titelsuche",
    "cb_show_variation",
    "cb_solution",
    "cb_drafts",
    "btn_suche",
    # "label_warnung",
]  #'actionRefresh_Database'

widgets_create = [
    "actionReset",
    # "menuBild_einbinden",
    # "menuSuche",
    # "menuSage",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    "groupBox_aufgabentyp",
    "groupBox_ausgew_gk_cr",
    "groupBox_variation_cr",
    "groupBox_bilder",
    "groupBox_titel_cr",
    "groupBox_grundkompetenzen_cr",
    "groupBox_punkte",
    "groupBox_klassen_cr",
    "groupBox_aufgabenformat",
    "groupBox_beispieleingabe",
    "groupBox_quelle",
    "pushButton_save",
]  #'actionRefresh_Database'


widgets_sage = [
    "actionLoad",
    "actionSave",
    "actionReset_sage",
    # "menuSuche",
    # "menuSage",
    # "menuNeu",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    "comboBox_at_sage",
    "groupBox_alle_aufgaben",
    "splitter_sage",
    "groupBox_sage",
    "comboBox_at_sage",
    "comboBox_gk",
    "comboBox_gk_num",
    "groupBox_default_pkt",
    "combobox_beurteilung",
    # "radioButton_notenschl",
    # "radioButton_beurteilungsraster",
]  # ,'comboBox_at_sage','groupBox_sage','groupBox_notenschl','actionRefresh_Database'


widgets_feedback = [
    # "menuSuche",
    # "menuSage",
    # "menuNeu",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    "comboBox_at_fb",
    "label_example",
    "groupBox_alle_aufgaben_fb",
    "groupBox_fehlertyp",
    "groupBox_feedback",
    "groupBox_email",
    "pushButton_send",
]

widgets_edit = [
    "actionReset",
    # "menuBild_einbinden",
    # "menuSuche",
    # "menuSage",
    # "menuNeu",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    "groupBox_aufgabentyp",
    "groupBox_ausgew_gk_cr",
    "groupBox_choose_file",
    "groupBox_bilder",
    "groupBox_titel_cr",
    "groupBox_grundkompetenzen_cr",
    "groupBox_punkte",
    "groupBox_klassen_cr",
    "groupBox_aufgabenformat",
    "groupBox_beispieleingabe",
    "groupBox_quelle",
    "pushButton_save_edit",
]  #'actionRefresh_Database'

################# LaMA Cria

widgets_search_cria = [
    # "actionRefresh_Database",
    "actionReset",
    "actionLoad",
    "actionSave",
    # "menuSage",
    # "menuNeu",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    # "label_update",
    "groupBox_ausgew_themen_cria",
    # "groupBox_ausgew_gk",
    "groupBox_af",
    "groupBox_schulstufe_cria",
    "groupBox_titelsuche",
    "groupBox_unterkapitel_cria",
    "cb_show_variation",
    "cb_solution",
    "cb_drafts",
    "btn_suche",
    "combobox_searchtype",
]

widgets_sage_cria = [
    "actionLoad",
    "actionSave",
    "actionReset_sage",
    # "menuSuche",
    # "menuNeu",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    "groupBox_alle_aufgaben",
    "splitter_sage",
    "groupBox_sage",
    "comboBox_klassen",
    "comboBox_kapitel",
    "comboBox_unterkapitel",
]  # ,'comboBox_at_sage','groupBox_sage','groupBox_notenschl','actionRefresh_Database'

widgets_create_cria = [
    "actionReset",
    # "menuBild_einbinden",
    # "menuSuche",
    # "menuSage",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    # "groupBox_aufgabentyp",
    "groupBox_ausgew_gk_cr",
    "groupBox_variation_cr",
    "groupBox_bilder",
    "groupBox_titel_cr",
    "groupBox_themengebiete_cria",
    # "groupBox_grundkompetenzen_cr",
    "groupBox_punkte",
    # "groupBox_klassen_cr",
    "groupBox_aufgabenformat",
    "groupBox_beispieleingabe",
    "groupBox_quelle",
    "pushButton_save",
]

widgets_feedback_cria = [
    # "menuSuche",
    # "menuSage",
    # "menuNeu",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    "comboBox_at_fb",
    "label_example",
    "comboBox_at_fb_cria",
    "groupBox_alle_aufgaben_fb_cria",
    "groupBox_fehlertyp",
    "groupBox_feedback",
    "groupBox_email",
    "pushButton_send",
]

list_widgets = [
    widgets_search,
    widgets_sage,
    widgets_create,
    widgets_feedback,
    widgets_edit,
    widgets_search_cria,
    widgets_sage_cria,
    widgets_create_cria,
    widgets_feedback_cria,
]

