# "menuDateityp",
# "menuNeu",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    # "label_update",
widgets_search = [
    "self.actionReset",
    'self.actionSage',
    "self.actionReset",
    "self.actionNeu",
    "self.actionEdit_Files",
    "self.actionFeedback",
    "self.tab_widget_gk",
    "self.combobox_aufgabentyp",
    "self.groupBox_klassen",
    "self.label_aufgabentyp",
    # "self.frame_tab_widget_gk",
    # "widget_headMenu",
    # "widget_searchMenu",
    # "groupBox_klassen",
    # "horizontalLayout_aufgabentyp",
    # "combobox_searchtype",
    # "label_aufgabentyp",
    # "combobox_aufgabentyp",
    # "groupBox_ausgew_gk",
    # "groupBox_af",
    # "frame_tab_widget_gk",
    # "tab_widget_gk",
    # "frame_ausgew_gk",
    # "groupBox_gk",
    # "groupBox_klassen",
    # "groupBox_themen_klasse",
    # "groupBox_advanced_search",
    # "cb_show_variation",
    # "cb_solution",
    # "cb_drafts",
    # "cb_infos",
    # "btn_suche",
    # "label_warnung",
]  #'actionRefresh_Database'

widgets_create = [
    "self.actionReset",
    "self.actionSuche",
    "self.actionReset",
    'self.actionSage',
    "self.actionEdit_Files",
    "self.actionFeedback",
    "self.groupBox_variation_cr",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    # "widget_basic_settings_creator",
    # "groupBox_aufgabentyp",
    # "groupBox_ausgew_gk_cr",
    # "groupBox_variation_cr",
    # "groupBox_bilder",
    # "groupBox_titel_cr",
    # "groupBox_grundkompetenzen_cr",
    # "groupBox_punkte",
    # "groupBox_klassen_cr",
    # "groupBox_aufgabenformat",
    # "groupBox_pagebreak",
    # "groupBox_abstand",
    # "groupBox_beispieleingabe",
    # "groupBox_quelle",
    # "pushButton_vorschau_edit",
    # "pushButton_save",
]  #'actionRefresh_Database'


widgets_sage = [
    "self.actionSave",
    "self.actionReset_sage",
    "self.actionSuche",
    "self.actionReset",
    'self.actionSave',
    "self.actionNeu",
    "self.actionEdit_Files",
    "self.actionFeedback",
    "self.comboBox_at_sage",
    "self.comboBox_gk",
    "self.comboBox_gk_num",
    # "menuFeedback",
    # "menuOptionen",
    # "menuHelp",
    # "menuDeveloper",
    # "comboBox_at_sage",
    # "groupBox_alle_aufgaben",
    # "splitter_sage",
    # "groupBox_sage",
    # "comboBox_at_sage",
    # "comboBox_gk",
    # "comboBox_gk_num",
    # "groupBox_default_pkt",
    # "combobox_beurteilung",
    # "label_gesamtpunkte",
    # "label_gesamtbeispiele",
    # "cb_drafts_sage",
    # "cb_solution_sage",
    # "label_gruppe_AB",
    # "comboBox_gruppe_AB",
    # "pushButton_vorschau",
    # "pushButton_erstellen",
    # "radioButton_notenschl",
    # "radioButton_beurteilungsraster",
]  # ,'comboBox_at_sage','groupBox_sage','groupBox_notenschl','actionRefresh_Database'


widgets_feedback = [
    "self.actionSuche",
    "self.actionReset",
    'self.actionSage',
    "self.actionNeu",
    "self.actionEdit_Files",
#     "comboBox_at_fb",
#     "label_example",
#     "groupBox_alle_aufgaben_fb",
#     "groupBox_fehlertyp",
#     "groupBox_feedback",
#     "groupBox_email",
#     "pushButton_send",
    ]

widgets_edit = [
    "self.actionReset",
    "self.actionSuche",
    "self.actionReset",
    'self.actionSage',
    "self.actionNeu",
    "self.actionFeedback",
    "self.groupBox_choose_file",
    # # "menuFeedback",
    # # "menuOptionen",
    # # "menuHelp",
    # # "menuDeveloper",
    # # "groupBox_aufgabentyp",
    # "groupBox_ausgew_gk_cr",
    # "groupBox_choose_file",
    # "groupBox_bilder",
    # "groupBox_titel_cr",
    # "groupBox_grundkompetenzen_cr",
    # "widget_basic_settings_creator",
    # "groupBox_punkte",
    # # "groupBox_klassen_cr",
    # "groupBox_aufgabenformat",
    # # "groupBox_pagebreak",
    # # "groupBox_abstand",
    # "groupBox_beispieleingabe",
    # "groupBox_quelle",
    # "pushButton_save_edit",
    # "pushButton_vorschau_edit",
    # "pushButton_delete_file",
    # "pushButton_save_as_variation_edit",
]  #'actionRefresh_Database'

################# LaMA Cria

widgets_search_cria = [
    "self.actionReset",
    'self.actionSage',
    "self.actionNeu",
    "self.actionEdit_Files",
    "self.actionFeedback",
    "self.combobox_searchtype",
    "self.tab_widget_search_cria",
    # "self.tab_widget_search_cria",
    # # "widget_headMenu",
    # # "label_aufgabentyp",
    # # "combobox_aufgabentyp",
    # # "menuFeedback",
    # # "menuOptionen",
    # # "menuHelp",
    # # "menuDeveloper",
    # # "label_update",
    # "widget_searchMenu",
    # "frame_tab_widget_gk",
    # "tab_widget_search_cria",
    # # "groupBox_themengebiete_cria",
    # "groupBox_ausgew_gk",
    # "groupBox_af",
    # # "groupBox_schulstufe_cria",
    # # "groupBox_advanced_search",
    # # "groupBox_unterkapitel_cria",
    # # "cb_show_variation",
    # # "cb_solution",
    # # "cb_drafts",
    # # "cb_infos",
    # "btn_suche",
    # "combobox_searchtype",
]

widgets_sage_cria = [
    # "actionLoad",
    "self.actionSave",
    "self.actionReset_sage",
    "self.actionSuche",
    "self.actionReset",
    'self.actionSave',
    # "menuNeu",
    "self.actionNeu",
    "self.actionEdit_Files",
    "self.actionFeedback",
    "self.comboBox_klassen",
    "self.comboBox_kapitel",
    "self.comboBox_unterkapitel",
    # # "menuFeedback",
    # # "menuOptionen",
    # # "menuHelp",
    # # "menuDeveloper",
    # "groupBox_alle_aufgaben",
    # "splitter_sage",
    # "groupBox_sage",
    # "comboBox_klassen",
    # "comboBox_kapitel",
    # "comboBox_unterkapitel",
    # "combobox_beurteilung",
    # # "label_gesamtpunkte",
    # # "label_gesamtbeispiele",
    # # "cb_drafts_sage",
    # # "cb_solution_sage",
    # # "label_gruppe_AB",
    # # "comboBox_gruppe_AB",
    # # "pushButton_vorschau",
    # # "pushButton_erstellen",
]  # ,'comboBox_at_sage','groupBox_sage','groupBox_notenschl','actionRefresh_Database'

widgets_create_cria = [
    "self.actionReset",
    # "menuBild_einbinden",
    "self.actionSuche",
    "self.actionReset",
    'self.actionSage',
    # "menuNeu",
    "self.actionEdit_Files",
    "self.actionFeedback",
    # # "menuFeedback",
    # # "menuOptionen",
    # # "menuHelp",
    # # "menuDeveloper",
    # # "groupBox_aufgabentyp",
    # "groupBox_ausgew_gk_cr",
    # "groupBox_variation_cr",
    # "groupBox_bilder",
    # "groupBox_titel_cr",
    # "groupBox_themengebiete_cria",
    # "widget_basic_settings_creator",
    # # "groupBox_grundkompetenzen_cr",
    # "groupBox_punkte",
    # # "groupBox_klassen_cr",
    # "groupBox_aufgabenformat",
    # # "groupBox_pagebreak",
    # # "groupBox_abstand",
    # "groupBox_beispieleingabe",
    # "groupBox_quelle",
    # "pushButton_vorschau_edit",
    # "pushButton_save",
]

widgets_edit_cria = [
    "self.actionReset",
    # "menuBild_einbinden",
    "self.actionSuche",
    "self.actionReset",
    'self.actionSage',
    # "menuNeu",
    "self.actionNeu",
    "self.actionFeedback",
    # # "menuFeedback",
    # # "menuOptionen",
    # # "menuHelp",
    # # "menuDeveloper",
    # # "groupBox_aufgabentyp",
    # "groupBox_ausgew_gk_cr",
    # "groupBox_choose_file",
    # "groupBox_bilder",
    # "groupBox_titel_cr",
    # "groupBox_themengebiete_cria",
    # "widget_basic_settings_creator",
    # # "groupBox_grundkompetenzen_cr",
    # # "groupBox_punkte",
    # # "groupBox_klassen_cr",
    # # "groupBox_aufgabenformat",
    # # "groupBox_abstand",
    # # "groupBox_pagebreak",
    # "groupBox_beispieleingabe",
    # "groupBox_quelle",
    # "pushButton_save_edit",
    # "pushButton_delete_file",
    # "pushButton_vorschau_edit",
    # "pushButton_save_as_variation_edit",
]

widgets_feedback_cria = [
    "self.actionSuche",
    "self.actionReset",
    'self.actionSage',
    "self.actionNeu",
    "self.actionEdit_Files",
    # # "menuOptionen",
    # # "menuHelp",
    # # "menuDeveloper",
    # "comboBox_at_fb",
    # "label_example",
    # "comboBox_at_fb_cria",
    # "groupBox_alle_aufgaben_fb_cria",
    # "groupBox_fehlertyp",
    # "groupBox_feedback",
    # "groupBox_email",
    # "pushButton_send",
]

widgets_wizard = [
    # 'comboBox_themen_wizard',
    # 'pushButton_create_worksheet_wizard',
    # 'groupBox_setting_wizard',
    # 'buttonBox_create_worksheet_wizard',
    # 'pushButton_add_to_worksheet_wizard',
    # 'scrollArea_chosen_wizard',
    # 'checkbox_solutions_wizard',
    # 'groupBox_titel_wizard',
    # "actionSave",
    # "actionReset_sage",
    # "actionSuche",
    # "actionReset",
    # 'actionSave',
    # "actionNeu",
    # "actionEdit_Files",
    # "actionFeedback",
    # "comboBox_at_sage",
    # "groupBox_alle_themen_wizard",
    # "splitter_wizard",
    # "groupBox_wizard",
    # "comboBox_at_wizard",
    # "comboBox_gk",
    # "comboBox_gk_num",
    # "groupBox_default_pkt",
    # "combobox_beurteilung",
]

list_widgets = [
    widgets_search,
    widgets_sage,
    widgets_create,
    widgets_feedback,
    widgets_edit,
    widgets_search_cria,
    widgets_sage_cria,
    widgets_create_cria,
    widgets_edit_cria,
    widgets_feedback_cria,
    widgets_wizard
]

